### ISSUE TITLE
How to define dispatch organization & project names for Slack plug-in 

### ISSUE THREAD

**Issue by olam-slack** [Netflix/dispatch-docker#132]
Hi, 

I have started a dispatch server locally. In addition, following your [configuration guide for Slack](https://hawkins.gitbook.io/dispatch/administration-guide/incident/plugins/configuring-slack) "(This process has to be daemonized similarly to the dispatch webserver.)", I have initialized a process by adding the following to my docker-compose.yml file.
```
  slack:
    <<: *restart_policy
    image: dispatch-local
    depends_on:
      - postgres
      - core
    env_file:
      - .env
    command: ["server", "slack", "default", "default"]
    ports:
      - 3001:8000      

```
I checked the log, I got an error:
"No slack plugin has been configured for this organization/plugin. Organization: default Project: <Project #1>"

- I have first kept the default names of organization and project, so I did not expect that this should happen.
- I then tried to change them, but then got an error that I reported on https://github.com/Netflix/dispatch-docker/issues/131
- I was then looking for an option to set these via .env, but this does not seem possible.

Thanks for your help in advance.
