### ISSUE TITLE
Connection Refused by dispatch container

### ISSUE THREAD

**Issue by njoerd114** [Netflix/dispatch-docker#19]
I can't seem to get dispatch running behind a reverse proxy (using Traefik for the sake of simplicity here)

I modified the docker-compose.yml to include traefik:
```
version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped
x-dispatch-defaults: &dispatch_defaults
  <<: *restart_policy
  build:
    context: ../dispatch/
    dockerfile: docker/Dockerfile
  image: dispatch-local:latest
  depends_on:
    - postgres
  env_file:
    - .env
services:
  postgres:
    <<: *restart_policy
    image: "postgres:9.6"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    <<: *dispatch_defaults
    labels:
          - "traefik.enable=true"
          - "traefik.http.routers.dispatch.rule=Host(`dispatch.local`)"
          - "traefik.http.routers.dispatch.entrypoints=web"
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  dispatch-scheduler:
    <<: *dispatch_defaults
volumes:
  dispatch-postgres:
    external: true
```

This brings up traefik and sets the routes correctly. However, if I try to connect to it I get an 502 Bad Request by traefik which is caused by a connection refused error from uvicorn.

Uvicorns default is to bind to 127.0.0.1 and I couldn't find a setting in the dispatch repo that would bind to 0.0.0.0 instead.

So I patched the run.py, [according to the docs:](https://www.uvicorn.org/settings/)
```
import uvicorn

if __name__ == "__main__":
    uvicorn.run("dispatch.main:app", host="0.0.0.0")
```
I then execed into the dispatch container, and installed netstat to figure out what's going on:
```
root@f341e4afc781:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38149        0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      1/python            
udp        0      0 127.0.0.11:36548        0.0.0.0:*                           -           
```
Everything looking good there. However, this still does not work :sob: 

Any suggestions? What's refusing the connection here?
