### ISSUE TITLE
web container set to listen on 127.0.0.1 - not able to access web UI externally

### ISSUE THREAD

**Issue by sarahcthekey** [Netflix/dispatch-docker#32]
Hi, not sure if you can double check the dispatch web image used in your install script, it doesn't appear to be using an image which starts dispatch web UI in the container on 0.0.0.0.

The web app container is listening on localhost only, rather than 0.0.0.0 so no traffic is being passed through from external with a docker port forward, and can't reach from other docker containers either. I've tried many network troubleshooting and came to this conclusion, I managed to get it working in the end. 

The Dockerfile in your dispatch repo : https://github.com/Netflix/dispatch/blob/develop/docker/Dockerfile

States...

```
ENTRYPOINT ["dispatch"]
CMD ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
```

So I built the docker image locally using this Dockerfile, then ran:
docker run dispatch-web --detach --env-file ../dispatch-docker/.env

I can now access publicly. So it's an issue in the Docker Compose build script, it must be ignoring the --host=0.0.0.0 when starting dispatch or Docker Compose is building from a Docker image not based on the Dockerfile containing the host config?

**Comment by B3lak0r** [comment]
@sarahcthekey , it will be possible to detail how you built the image locally?

**Comment by sarahcthekey** [comment]
@B3lak0r I've found the missing piece of the puzzle...

Append the docker-compose.yml line number 26:

`CMD ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]`

**Comment by B3lak0r** [comment]
@sarahcthekey but on my docker-compose.yml what I actually have is the volume detailed: 

version: "3.4"
x-restart-policy: &restart_policy
restart: unless-stopped
x-dispatch-defaults: &dispatch_defaults
<<: *restart_policy
env_file:
- .env
build:
# Pro-tip: point this to a relative directory containing the Dispatch
# project root to pick up changes from your dev environment
# (e.g., ../dispatch-root)
context: https://github.com/Netflix/dispatch.git#develop:.
image: dispatch-local
depends_on:
- postgres
env_file:
- .env
services:
postgres:
<<: *restart_policy
env_file:
- .env
image: "postgres:9.6"
ports:
- "5432:5432"
volumes:
- "dispatch-postgres:/var/lib/postgresql/data"
env_file: ./.env
web:
<<: *dispatch_defaults
command: ["server", "start", "dispatch.main:app"]
ports:
- "8000:8000"
dispatch-scheduler:
<<: *dispatch_defaults
command: ["scheduler", "start"]
ports:
- "8001:8000"
volumes:
dispatch-postgres:
external: true

Could you share yours then ? sorry to ask for that

**Comment by sarahcthekey** [comment]
@B3lak0r Sure no problem, here's the full docker-compose.yml file:

```
version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped
services:
  postgres:
    <<: *restart_policy
    env_file:
      - .env
    image: "postgres:9.6"
    ports:
      - "5432:5432"
    volumes:
      - "dispatch-postgres:/var/lib/postgresql/data"
  web:
    <<: *restart_policy
    build:
      # Pro-tip: point this to a relative directory containing the Dispatch
      # project root to pick up changes from your dev environment
      # (e.g., ../dispatch-root)
      context: https://github.com/Netflix/dispatch.git#develop:.
    image: dispatch-local-web
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
    ports:
    - "80:8000"
  scheduler:
    <<: *restart_policy
    build:
      # Pro-tip: point this to a relative directory containing the Dispatch
      # project root to pick up changes from your dev environment
      # (e.g., ../dispatch-root)
      context: https://github.com/Netflix/dispatch.git#develop:.
      args:
        DISPATCH_LIGHT_BUILD: "1"
    image: dispatch-local-scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["scheduler", "start"]
    ports:
    - "8000:8000"
volumes:
  dispatch-postgres:
    external: true
```
